#!/usr/bin/env bash
##############################################################################
# Copyright 2013 Institute for Molecular Imaging Instrumentation (I3M)
# 
# Licensed under the EUPL, Version 1.1 or - as soon they will be approved by 
# the European Commission - subsequent versions of the EUPL (the "Licence");
# You may not use this work except in compliance with the Licence.
# You may obtain a copy of the Licence at:
#
#   http://ec.europa.eu/idabc/eupl
#
# Unless required by applicable law or agreed to in writing, software 
# distributed under the Licence is distributed on an "AS IS" basis,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the Licence for the specific language governing permissions and 
# limitations under the Licence.
#
# This product combines work with different licenses. See the "NOTICE" text
# file for details on the various modules and licenses.
# The "NOTICE" text file is part of the distribution. Any derivative works
# that you distribute must include a readable copy of the "NOTICE" text file.
##############################################################################

##############################################################################
# Usage examples:
#
# 1) start/stop the DICOM graph study service:
#  
#    gpf4med start/stop
#
# 2) check the status of the service:
#
#    gpf4med status
#
# 3) do not execute operation, just print Java command:
#
#    RUN_JAVA_DRY=1 gpf4med start
##############################################################################

# stop on errors
set -e

SCRIPT_NAME=$(basename $0)

# resolve to absolute path where this script run
if [ ! -h $0 ]; then
  SCRIPT_DIR=$(cd $(dirname $0) && pwd)
else
  SCRIPT_DIR=$(cd $(dirname $(readlink $0)) && pwd)
fi

APP_NAME=gpf4med
APP_DIR=$(dirname $SCRIPT_DIR)
APP_CONFIG=${APP_DIR}/etc
APP_JARFILE=${APP_DIR}/lib/java/gpf4med.jar
APP_PIDFILE=${APP_DIR}/var/run/${APP_NAME}.pid

if [[ ! -e "${APP_DIR}" || ! -d "${APP_DIR}" ]] ; then
  echo "Base directory $APP_DIR does not exist or is not a directory. Exiting..."
  exit 1
fi

# resolve Java home
_JAVA_HOME=$(readlink -f /usr/bin/java | sed "s:bin/java::")
JAVA_HOME=${JAVA_HOME:=$_JAVA_HOME}

# resolve Java command
JAVA_CMD=java
if [ -d "$JAVA_HOME" ]; then
  JAVA_CMD="$JAVA_HOME/bin/java"
fi

# detect Java version
if type -p "$JAVA_CMD" 1>/dev/null 2>&1; then
  JAVA_VERSION=$("$JAVA_CMD" -version 2>&1 | awk -F '"' '/version/ {print $2}')
  if [[ "$JAVA_VERSION" < "1.7" ]]; then
    echo "Java version is less than 1.7. Exiting..."
    exit 1
  fi
else
  echo "No Java installation found. Exiting..."
  exit 1
fi

start_container()
{
  # get machine type
  if [ `getconf LONG_BIT` = "64" ]
  then
    MACHINE_TYPE="-d64"
  else
    MACHINE_TYPE=""
  fi

  # compute maximum available memory as: pow(2, ceil(log(x)/log(2)))
  MAX_MEMORY=$(echo "2^($(grep MemTotal /proc/meminfo | echo "l(`awk '{print $2}'`*0.75/1024)/l(2)" | bc -l) / 1)" | bc)

  # JVM optimization
  JVM_OPTIMIZATION="-XX:+UseNUMA -XX:+UseParallelGC"
  #JVM_OPTIMIZATION="-XX:+UseConcMarkSweepGC"

  # default parameters
  RUN_JAVA_OPTS="$MACHINE_TYPE -server -Xmx${MAX_MEMORY}m -Xss1024k $JVM_OPTIMIZATION"
  RUN_JAVA_DRY=${RUN_JAVA_DRY:=} # Do not execute when is not empty, but just print
  
  RUN_JAVA_OPTS="$RUN_JAVA_OPTS -Dlogback.configurationFile=${APP_CONFIG}/logback.xml"
  RUN_APP_OPTS="-jar $APP_JARFILE -d -c $APP_CONFIG"
  
  # display full Java command
  if [ -n "$RUN_JAVA_DRY" ]; then
    echo "$JAVA_CMD $RUN_JAVA_OPTS $RUN_APP_OPTS"
  fi

  # run Java main class
  if [ -z "$RUN_JAVA_DRY" ]; then
    # exit if PID file exists
    if [ -e $APP_PIDFILE ]; then
      echo "Pid file $APP_PIDFILE already exists. Exiting..."
      exit 1
    fi
    # lock PID file
    exec 200>$APP_PIDFILE
    flock -n 200 || exit 1
    # run service container
    $JAVA_CMD $RUN_JAVA_OPTS $RUN_APP_OPTS &
    echo $! 1>&200
    echo "$APP_NAME is running"
  fi
}

stop_container()
{
  if [ -e $APP_PIDFILE ] && [ -f $APP_PIDFILE ]; then
    PID=$(cat $APP_PIDFILE)
    if ps -p $PID > /dev/null 2>&1; then
      if ! kill -s TERM $PID > /dev/null 2>&1; then
        echo "Could not sent SIGTERN to process $PID. $APP_NAME was not stopped" >&2
        exit 2
      fi
    fi
    rm -f $APP_PIDFILE
    if [ "$?" -eq 0 ]; then
      echo "$APP_NAME is stopped"
    else
      echo "$APP_NAME is stopped, but $APP_PIDFILE cannot removed"
    fi
  else
    echo "$APP_NAME is stopped, $APP_PIDFILE not found"
  fi
}

container_status()
{
  if [ -e $APP_PIDFILE ] && [ -f $APP_PIDFILE ]; then
    PID=$(cat $APP_PIDFILE)
    if [ -e /proc/${PID} -a /proc/${PID}/exe -ef $JAVA_CMD ] && [ -n "`grep ${APP_NAME} /proc/${PID}/cmdline`" ] ; then
      echo "$APP_NAME is running"
    else
      echo "$APP_NAME is stopped"
    fi
  else
    if [ -n "`ps ax | grep ${APP_NAME} | grep -v grep`" ]; then
      echo "$APP_NAME is stopped"
    else
      echo "$APP_NAME is running, but $APP_PIDFILE is unavailable"
    fi
  fi
}

case "$1" in
  start)
        start_container
        ;;
  stop)
        stop_container
        ;;
  status)
        container_status
        ;;
  *)
        echo "Usage: $SCRIPT_DIR/$SCRIPT_NAME {start|stop|status}" >&2
        exit 3
        ;;
esac
